# fly.toml app configuration file generated for gogym on 2024-05-20T23:42:38+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gogym'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]
  image = "registry.fly.io/gogym:latest"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[deploy]
  release_command = "/rails/bin/rails db:migrate"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "assets_volume_1"
  destination = "/app/public/assets"
